[package]
name = "cvlcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"

[target.'cfg(windows)'.dependencies]
opencv = "0.82.0"

[target.'cfg(macos)'.dependencies]
opencv = "0.76.4"

[target.'cfg(unix)'.dependencies]
opencv = "0.82.4"

[[example]]
name = "web_cam_example"

[[example]]
name = "file_example"
