name: GitHub Pages
on:
  push:
    branches:
      - 'release/**'
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install prerequisites
        run: |
            sudo apt update
            sudo apt install -y build-essential curl \
              cmake clang libclang-dev llvm llvm-dev \
              qt5-default libopencv-dev \
              python3-dev python3-numpy python3-opencv
    
      - uses: actions/checkout@v2
      - name: Build the doc
        run: |
          cargo doc --all-features --no-deps
          echo "<meta http-equiv=refresh content=0;url=numpy/index.html>" > target/doc/index.html
    
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/
          destination_dir: .
          full_commit_message: 'Upload documentation for current release'
