name: Pull Request Checking

run-name: ${{ github.actor }} is building action
on:
  pull_request_target:
    types: [ assigned, opened, synchronize, reopened ]
  push:
    branches:
      - 'master'
      - 'actions/**'
      - 'release/**'

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential curl \
            cmake clang libclang-dev llvm llvm-dev \
            qt5-default libopencv-dev \
            python3-dev python3-numpy python3-opencv
          
      - uses: actions/checkout@v3
      - name: Build project
        run: cargo build --verbose --jobs $(nproc)
        
      - name: Run tests
        run: cargo test --verbose
        
      - name: Build docs
        run: cargo doc --verbose
