name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
    - uses: Dovyski/setup-opencv-action@v1.1
      with:
        opencv-version: '4.0.0'

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

  tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Run tests
      run: cargo test --verbose
      
