name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  OPENCV_LINK_LIBS: opencv_highgui, opencv_objdetect, opencv_dnn, opencv_videostab, opencv_calib3d, opencv_features2d, opencv_stitching, opencv_flann, opencv_videoio, opencv_rgbd, opencv_aruco, opencv_video, opencv_ml, opencv_imgcodecs, opencv_imgproc, opencv_core, ittnotify, tbb, liblibwebp, liblibtiff, liblibjpeg-turbo, liblibpng, liblibopenjp2, ippiw, ippicv, liblibprotobuf, quirc, zlib
  OPENCV_LINK_PATHS: /usr/local/lib
  OPENCV_INCLUDE_PATHS: /usr/local/include/opencv4

jobs:
  dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake clang \
            libclang-dev llvm llvm-dev qt5-default libopencv-dev
      
      - uses: Dovyski/setup-opencv-action@v1.1        
        with:
          opencv-version: '4.6.0'
          
      - uses: actions/checkout@v3
      - name: Build project
        run: cargo build --verbose --jobs $(nproc)
        
      - name: Run tests
        run: cargo test --verbose
        
      - name: Build docs
        run: |
          cargo doc --verbose 
          mv target/doc target/release/
